
SET IDENTITY_INSERT [Product].[ActiveIngredient] ON;

INSERT INTO [Product].[ActiveIngredient] (ActiveIngredientID, ActiveIngredientName, ActiveIngredienDescription, StateID) VALUES
(1,'Paracetamol','Principio activo utilizado como analgésico y antipirético',1),
(2,'Ibuprofeno','Principio activo utilizado como antiinflamatorio no esteroideo',1),
(3,'Amoxicilina','Principio activo utilizado como antibiótico betalactámico',1),
(4,'Omeprazol','Principio activo utilizado para inhibir la secreción gástrica',1),
(5,'Losartán','Principio activo utilizado como antihipertensivo',1),
(6,'Metformina','Principio activo utilizado para el tratamiento de diabetes tipo 2',1),
(7,'Simvastatina','Principio activo utilizado para reducir colesterol',1),
(8,'Aspirina','Principio activo utilizado como analgésico y antiagregante',1),
(9,'Claritromicina','Principio activo utilizado como antibiótico macrólido',1),
(10,'Captopril','Principio activo utilizado como inhibidor de la ECA',1),
(11,'Dexametasona','Principio activo utilizado como corticosteroide',1),
(12,'Alprazolam','Principio activo utilizado como ansiolítico benzodiacepínico',1),
(13,'Citalopram','Principio activo utilizado como antidepresivo ISRS',1),
(14,'Prednisona','Principio activo utilizado como corticosteroide antiinflamatorio',1),
(15,'Furosemida','Principio activo utilizado como diurético de asa',1),
(16,'Warfarina','Principio activo utilizado como anticoagulante',1),
(17,'Levotiroxina','Principio activo utilizado para hipotiroidismo',1),
(18,'Losartán potásico','Principio activo utilizado como antihipertensivo',1),
(19,'Azitromicina','Principio activo antibiótico de amplio espectro',1),
(20,'Clindamicina','Principio activo utilizado como antibiótico lincosamida',1),
(21,'Salbutamol','Principio activo utilizado como broncodilatador',1),
(22,'Insulina','Principio activo utilizado en el manejo de diabetes',1),
(23,'Hidrocortisona','Principio activo utilizado como corticosteroide',1),
(24,'Ketorolaco','Principio activo utilizado como analgésico potente',1),
(25,'Enalapril','Principio activo utilizado como inhibidor de la ECA',1),
(26,'Atorvastatina','Principio activo utilizado para disminuir lípidos',1),
(27,'Clotrimazol','Principio activo antifúngico',1),
(28,'Loratadina','Principio activo antihistamínico',1),
(29,'Ranitidina','Principio activo utilizado para reducir ácido gástrico',1),
(30,'Fluconazol','Principio activo antifúngico triazólico',1),
(31,'Naproxeno','Principio activo antiinflamatorio no esteroideo',1),
(32,'Budesonida','Principio activo corticosteroide para enfermedades respiratorias',1),
(33,'Levofloxacino','Principio activo antibiótico fluoroquinolona',1),
(34,'Gentamicina','Principio activo antibiótico aminoglucósido',1),
(35,'Doxiciclina','Principio activo antibiótico tetraciclina',1),
(36,'Metronidazol','Principio activo utilizado contra anaerobios y protozoos',1),
(37,'Cefalexina','Principio activo antibiótico cefalosporina',1),
(38,'Pantoprazol','Principio activo para reducción de ácido gástrico',1),
(39,'Tramadol','Principio activo analgésico opioide débil',1),
(40,'Carbamazepina','Principio activo utilizado como anticonvulsivo',1),
(41,'Gabapentina','Principio activo para dolor neuropático y convulsiones',1),
(42,'Diltiazem','Principio activo bloqueador de canal de calcio',1),
(43,'Verapamilo','Principio activo bloqueador de canal de calcio',1),
(44,'Propranolol','Principio activo betabloqueante',1),
(45,'Metoprolol','Principio activo betabloqueante selectivo',1),
(46,'Atenolol','Principio activo betabloqueante selectivo',1),
(47,'Clonazepam','Principio activo ansiolítico anticonvulsivo',1),
(48,'Diazepam','Principio activo ansiolítico benzodiacepínico',1),
(49,'Sertralina','Principio activo antidepresivo ISRS',1),
(50,'Escitalopram','Principio activo antidepresivo ISRS',1),
(51,'Tamsulosina','Principio activo para hiperplasia prostática benigna',1),
(52,'Finasterida','Principio activo para alopecia y HBP',1),
(53,'Allopurinol','Principio activo para gota',1),
(54,'Levamisol','Principio activo antiparasitario',1),
(55,'Ivermectina','Principio activo antiparasitario',1),
(56,'Albendazol','Principio activo antiparasitario de amplio espectro',1),
(57,'Oxibutinina','Principio activo para vejiga hiperactiva',1),
(58,'Tolterodina','Principio activo antimuscarínico',1),
(59,'Sulfasalazina','Principio activo para enfermedades inflamatorias',1),
(60,'Mesalazina','Principio activo antiinflamatorio intestinal',1),
(61,'Azatioprina','Principio activo inmunosupresor',1),
(62,'Ciclosporina','Principio activo inmunosupresor',1),
(63,'Tacrolimus','Principio activo inmunosupresor',1),
(64,'Interferón alfa','Principio activo antiviral e inmunomodulador',1),
(65,'Ribavirina','Principio activo antiviral',1),
(66,'Oseltamivir','Principio activo antiviral para influenza',1),
(67,'Aciclovir','Principio activo antiviral',1),
(68,'Valaciclovir','Principio activo antiviral',1),
(69,'Lamivudina','Principio activo antiviral',1),
(70,'Tenofovir','Principio activo antiviral',1),
(71,'Efavirenz','Principio activo antiviral',1),
(72,'Zidovudina','Principio activo antiviral',1),
(73,'Abacavir','Principio activo antiviral',1),
(74,'Nevirapina','Principio activo antiviral',1),
(75,'Dolutegravir','Principio activo antiviral',1),
(76,'Raltegravir','Principio activo antiviral',1),
(77,'Maraviroc','Principio activo antiviral',1),
(78,'Enfuvirtida','Principio activo antiviral',1),
(79,'Gemfibrozil','Principio activo para dislipidemia',1),
(80,'Fenofibrato','Principio activo para lípidos',1),
(81,'Niacina','Principio activo vitamina para lípidos',1),
(82,'Ácido fólico','Principio activo vitamina',1),
(83,'Vitamina B12','Principio activo vitamina',1),
(84,'Vitamina D3','Principio activo vitamina',1),
(85,'Calcio Carbonato','Principio activo mineral',1),
(86,'Hierro Sulfato','Principio activo mineral suplementario',1),
(87,'Magnesio','Principio activo mineral',1),
(88,'Potasio Cloruro','Principio activo mineral',1),
(89,'Ácido Ascórbico','Principio activo vitamina C',1),
(90,'Biotina','Principio activo vitamina B7',1),
(91,'Piridoxina','Principio activo vitamina B6',1),
(92,'Riboflavina','Principio activo vitamina B2',1),
(93,'Tiamina','Principio activo vitamina B1',1),
(94,'Niacinamida','Principio activo vitamina B3',1),
(95,'Retinol','Principio activo vitamina A',1),
(96,'Colecalciferol','Principio activo vitamina D',1),
(97,'Alpha‑Lipoico','Principio activo antioxidante',1),
(98,'Coenzima Q10','Principio activo antioxidante',1),
(99,'Luteína','Principio activo antioxidante',1),
(100,'EPA / DHA','Principio activo ácidos grasos omega‑3',1),
(101,'Glucosamina','Principio activo para soporte articular y cartílago',1),
(102,'Condroitina','Principio activo para salud de articulaciones',1),
(103,'Metoclopramida','Principio activo antiemético y procinético',1),
(104,'Ondansetrón','Principio activo antiemético selectivo',1),
(105,'Domperidona','Principio activo antiemético y motilidad gástrica',1),
(106,'Escopolamina','Principio activo antiespasmódico y antiemético',1),
(107,'Clonidina','Principio activo antihipertensivo y neurológico',1),
(108,'Metildopa','Principio activo antihipertensivo',1),
(109,'Hidralazina','Principio activo vasodilatador',1),
(110,'Nifedipino','Principio activo bloqueador de canal de calcio',1),
(111,'Amlodipino','Principio activo bloqueador de canal de calcio',1),
(112,'Felodipino','Principio activo bloqueador de canal de calcio',1),
(113,'Verapamilo','Principio activo bloqueador de canal de calcio',1),
(114,'Diltiazem','Principio activo bloqueador de canal de calcio',1),
(115,'Propranolol','Principio activo betabloqueante no selectivo',1),
(116,'Metoprolol','Principio activo betabloqueante selectivo',1),
(117,'Atenolol','Principio activo betabloqueante selectivo',1),
(118,'Carvedilol','Principio activo betabloqueante no selectivo',1),
(119,'Nebivolol','Principio activo betabloqueante selectivo',1),
(120,'Bisoprolol','Principio activo betabloqueante selectivo',1),
(121,'Losartán','Principio activo antihipertensivo antagonista de angiotensina II',1),
(122,'Valsartán','Principio activo antihipertensivo antagonista de angiotensina II',1),
(123,'Irbesartán','Principio activo antihipertensivo antagonista de angiotensina II',1),
(124,'Telmisartán','Principio activo antihipertensivo antagonista de angiotensina II',1),
(125,'Candesartán','Principio activo antihipertensivo antagonista de angiotensina II',1),
(126,'Hydroclorotiazida','Principio activo diurético tiazídico',1),
(127,'Clortalidona','Principio activo diurético tiazídico',1),
(128,'Furosemida','Principio activo diurético de asa',1),
(129,'Bumetanida','Principio activo diurético de asa',1),
(130,'Espironolactona','Principio activo diurético ahorrador de potasio',1),
(131,'Eplerenona','Principio activo diurético ahorrador de potasio',1),
(132,'Digoxina','Principio activo inotrópico positivo',1),
(133,'Amiodarona','Principio activo antiarrítmico clase III',1),
(134,'Sotalol','Principio activo antiarrítmico y betabloqueante',1),
(135,'Adenosina','Principio activo antiarrítmico',1),
(136,'Propafenona','Principio activo antiarrítmico clase IC',1),
(137,'Flecainida','Principio activo antiarrítmico clase IC',1),
(138,'Atorvastatina','Principio activo hipolipemiante',1),
(139,'Simvastatina','Principio activo hipolipemiante',1),
(140,'Rosuvastatina','Principio activo hipolipemiante',1),
(141,'Pravastatina','Principio activo hipolipemiante',1),
(142,'Lovastatina','Principio activo hipolipemiante',1),
(143,'Fenofibrato','Principio activo hipolipemiante',1),
(144,'Gemfibrozilo','Principio activo hipolipemiante',1),
(145,'Niacina','Principio activo hipolipemiante y vitamina',1),
(146,'Acetilcisteína','Principio activo mucolítico y antioxidante',1),
(147,'Bromhexina','Principio activo mucolítico',1),
(148,'Ambroxol','Principio activo mucolítico',1),
(149,'Salbutamol','Principio activo broncodilatador',1),
(150,'Fenoterol','Principio activo broncodilatador',1),
(151,'Formoterol','Principio activo broncodilatador',1),
(152,'Salmeterol','Principio activo broncodilatador',1),
(153,'Ipratropio','Principio activo anticolinérgico inhalado',1),
(154,'Tiotropio','Principio activo anticolinérgico inhalado',1),
(155,'Montelukast','Principio activo antagonista de leucotrienos',1),
(156,'Zafirlukast','Principio activo antagonista de leucotrienos',1),
(157,'Prednisona','Principio activo corticosteroide oral',1),
(158,'Metilprednisolona','Principio activo corticosteroide',1),
(159,'Hidrocortisona','Principio activo corticosteroide',1),
(160,'Budesonida','Principio activo corticosteroide inhalado',1),
(161,'Fluticasona','Principio activo corticosteroide inhalado',1),
(162,'Mometasona','Principio activo corticosteroide nasal',1),
(163,'Triamcinolona','Principio activo corticosteroide',1),
(164,'Dexametasona','Principio activo corticosteroide',1),
(165,'Betametasona','Principio activo corticosteroide',1),
(166,'Claritromicina','Principio activo antibiótico macrólido',1),
(167,'Eritromicina','Principio activo antibiótico macrólido',1),
(168,'Azitromicina','Principio activo antibiótico macrólido',1),
(169,'Cefalexina','Principio activo antibiótico cefalosporina de primera generación',1),
(170,'Cefuroxima','Principio activo antibiótico cefalosporina de segunda generación',1),
(171,'Ceftriaxona','Principio activo antibiótico cefalosporina de tercera generación',1),
(172,'Cefepima','Principio activo antibiótico cefalosporina de cuarta generación',1),
(173,'Amoxicilina','Principio activo antibiótico penicilina de amplio espectro',1),
(174,'Ampicilina','Principio activo antibiótico penicilina',1),
(175,'Piperacilina','Principio activo antibiótico penicilina de amplio espectro',1),
(176,'Ticarcilina','Principio activo antibiótico penicilina',1),
(177,'Vancomicina','Principio activo antibiótico glicopéptido',1),
(178,'Teicoplanina','Principio activo antibiótico glicopéptido',1),
(179,'Ciprofloxacino','Principio activo antibiótico fluoroquinolona',1),
(180,'Levofloxacino','Principio activo antibiótico fluoroquinolona',1),
(181,'Moxifloxacino','Principio activo antibiótico fluoroquinolona',1),
(182,'Ofloxacino','Principio activo antibiótico fluoroquinolona',1),
(183,'Metronidazol','Principio activo antibiótico y antiparasitario',1),
(184,'Tinidazol','Principio activo antibiótico y antiparasitario',1),
(185,'Clindamicina','Principio activo antibiótico lincosamida',1),
(186,'Linezolid','Principio activo antibiótico oxazolidinona',1),
(187,'Daptomicina','Principio activo antibiótico lipopeptídico',1),
(188,'Gentamicina','Principio activo antibiótico aminoglucósido',1),
(189,'Amikacina','Principio activo antibiótico aminoglucósido',1),
(190,'Tobramicina','Principio activo antibiótico aminoglucósido',1),
(191,'Kanamicina','Principio activo antibiótico aminoglucósido',1),
(192,'Rifampicina','Principio activo antibiótico antituberculoso',1),
(193,'Isoniazida','Principio activo antibiótico antituberculoso',1),
(194,'Etambutol','Principio activo antibiótico antituberculoso',1),
(195,'Pirazinamida','Principio activo antibiótico antituberculoso',1),
(196,'Aciclovir','Principio activo antiviral',1),
(197,'Valaciclovir','Principio activo antiviral',1),
(198,'Famciclovir','Principio activo antiviral',1),
(199,'Oseltamivir','Principio activo antiviral influenza',1),
(200,'Zanamivir','Principio activo antiviral influenza',1),
(201,'Lamivudina','Principio activo antiviral para VIH y hepatitis B',1),
(202,'Tenofovir','Principio activo antiviral para VIH y hepatitis B',1),
(203,'Efavirenz','Principio activo antiviral para VIH',1),
(204,'Zidovudina','Principio activo antiviral para VIH',1),
(205,'Abacavir','Principio activo antiviral para VIH',1),
(206,'Nevirapina','Principio activo antiviral para VIH',1),
(207,'Dolutegravir','Principio activo antiviral inhibidor de integrasa',1),
(208,'Raltegravir','Principio activo antiviral inhibidor de integrasa',1),
(209,'Maraviroc','Principio activo antiviral inhibidor de CCR5',1),
(210,'Enfuvirtida','Principio activo antiviral inhibidor de fusión',1),
(211,'Metformina','Principio activo para diabetes tipo 2',1),
(212,'Glipizida','Principio activo antidiabético sulfonilurea',1),
(213,'Glibenclamida','Principio activo antidiabético sulfonilurea',1),
(214,'Glimepirida','Principio activo antidiabético sulfonilurea',1),
(215,'Pioglitazona','Principio activo antidiabético tiazolidinediona',1),
(216,'Rosiglitazona','Principio activo antidiabético tiazolidinediona',1),
(217,'Insulina NPH','Principio activo insulina de acción intermedia',1),
(218,'Insulina Regular','Principio activo insulina de acción corta',1),
(219,'Insulina Glargina','Principio activo insulina de acción prolongada',1),
(220,'Insulina Lispro','Principio activo insulina de acción rápida',1),
(221,'Levotiroxina','Principio activo hormona tiroidea sintética',1),
(222,'Liotironina','Principio activo hormona tiroidea sintética T3',1),
(223,'Propiltiouracilo','Principio activo antitiroideo',1),
(224,'Metimazol','Principio activo antitiroideo',1),
(225,'Sotalol','Principio activo antiarrítmico y betabloqueante',1),
(226,'Amiodarona','Principio activo antiarrítmico clase III',1),
(227,'Propafenona','Principio activo antiarrítmico clase IC',1),
(228,'Flecainida','Principio activo antiarrítmico clase IC',1),
(229,'Adenosina','Principio activo antiarrítmico de acción corta',1),
(230,'Digoxina','Principio activo inotrópico positivo',1),
(231,'Enalapril','Principio activo inhibidor de la ECA',1),
(232,'Captopril','Principio activo inhibidor de la ECA',1),
(233,'Lisinopril','Principio activo inhibidor de la ECA',1),
(234,'Ramipril','Principio activo inhibidor de la ECA',1),
(235,'Losartán','Principio activo antagonista de angiotensina II',1),
(236,'Valsartán','Principio activo antagonista de angiotensina II',1),
(237,'Irbesartán','Principio activo antagonista de angiotensina II',1),
(238,'Telmisartán','Principio activo antagonista de angiotensina II',1),
(239,'Candesartán','Principio activo antagonista de angiotensina II',1),
(240,'Atenolol','Principio activo betabloqueante selectivo',1),
(241,'Metoprolol','Principio activo betabloqueante selectivo',1),
(242,'Propranolol','Principio activo betabloqueante no selectivo',1),
(243,'Carvedilol','Principio activo betabloqueante no selectivo',1),
(244,'Nebivolol','Principio activo betabloqueante selectivo',1),
(245,'Bisoprolol','Principio activo betabloqueante selectivo',1),
(246,'Hydroclorotiazida','Principio activo diurético tiazídico',1),
(247,'Clortalidona','Principio activo diurético tiazídico',1),
(248,'Furosemida','Principio activo diurético de asa',1),
(249,'Bumetanida','Principio activo diurético de asa',1),
(250,'Espironolactona','Principio activo diurético ahorrador de potasio',1),
(251,'Eplerenona','Principio activo diurético ahorrador de potasio',1),
(252,'Acetilcisteína','Principio activo mucolítico y antioxidante',1),
(253,'Ambroxol','Principio activo mucolítico',1),
(254,'Bromhexina','Principio activo mucolítico',1),
(255,'Salbutamol','Principio activo broncodilatador',1),
(256,'Fenoterol','Principio activo broncodilatador',1),
(257,'Formoterol','Principio activo broncodilatador',1),
(258,'Salmeterol','Principio activo broncodilatador',1),
(259,'Ipratropio','Principio activo anticolinérgico inhalado',1),
(260,'Tiotropio','Principio activo anticolinérgico inhalado',1),
(261,'Montelukast','Principio activo antagonista de leucotrienos',1),
(262,'Zafirlukast','Principio activo antagonista de leucotrienos',1),
(263,'Prednisona','Principio activo corticosteroide oral',1),
(264,'Metilprednisolona','Principio activo corticosteroide',1),
(265,'Hidrocortisona','Principio activo corticosteroide',1),
(266,'Budesonida','Principio activo corticosteroide inhalado',1),
(267,'Fluticasona','Principio activo corticosteroide inhalado',1),
(268,'Mometasona','Principio activo corticosteroide nasal',1),
(269,'Triamcinolona','Principio activo corticosteroide',1),
(270,'Dexametasona','Principio activo corticosteroide',1),
(271,'Betametasona','Principio activo corticosteroide',1),
(272,'Claritromicina','Principio activo antibiótico macrólido',1),
(273,'Eritromicina','Principio activo antibiótico macrólido',1),
(274,'Azitromicina','Principio activo antibiótico macrólido',1),
(275,'Cefalexina','Principio activo antibiótico cefalosporina de primera generación',1),
(276,'Cefuroxima','Principio activo antibiótico cefalosporina de segunda generación',1),
(277,'Ceftriaxona','Principio activo antibiótico cefalosporina de tercera generación',1),
(278,'Cefepima','Principio activo antibiótico cefalosporina de cuarta generación',1),
(279,'Amoxicilina','Principio activo antibiótico penicilina de amplio espectro',1),
(280,'Ampicilina','Principio activo antibiótico penicilina',1),
(281,'Piperacilina','Principio activo antibiótico penicilina de amplio espectro',1),
(282,'Ticarcilina','Principio activo antibiótico penicilina',1),
(283,'Vancomicina','Principio activo antibiótico glicopéptido',1),
(284,'Teicoplanina','Principio activo antibiótico glicopéptido',1),
(285,'Ciprofloxacino','Principio activo antibiótico fluoroquinolona',1),
(286,'Levofloxacino','Principio activo antibiótico fluoroquinolona',1),
(287,'Moxifloxacino','Principio activo antibiótico fluoroquinolona',1),
(288,'Ofloxacino','Principio activo antibiótico fluoroquinolona',1),
(289,'Metronidazol','Principio activo antibiótico y antiparasitario',1),
(290,'Tinidazol','Principio activo antibiótico y antiparasitario',1),
(291,'Clindamicina','Principio activo antibiótico lincosamida',1),
(292,'Linezolid','Principio activo antibiótico oxazolidinona',1),
(293,'Daptomicina','Principio activo antibiótico lipopeptídico',1),
(294,'Gentamicina','Principio activo antibiótico aminoglucósido',1),
(295,'Amikacina','Principio activo antibiótico aminoglucósido',1),
(296,'Tobramicina','Principio activo antibiótico aminoglucósido',1),
(297,'Kanamicina','Principio activo antibiótico aminoglucósido',1),
(298,'Rifampicina','Principio activo antibiótico antituberculoso',1),
(299,'Isoniazida','Principio activo antibiótico antituberculoso',1),
(300,'Etambutol','Principio activo antibiótico antituberculoso',1);

SET IDENTITY_INSERT [Product].[ActiveIngredient] OFF;