
INSERT INTO [Product].[PharmaceuticalForm] (PharmaceuticalFormName, PharmaceuticalFormDescription, StateID) VALUES
('Tableta','Comprimido sólido para administración oral',1),
('Cápsula dura','Cápsula sólida de gelatina dura',1),
('Cápsula blanda','Cápsula líquida o semilíquida de gelatina blanda',1),
('Tableta masticable','Comprimido que se mastica antes de tragar',1),
('Tableta efervescente','Comprimido que se disuelve en agua antes de su administración',1),
('Tableta sublingual','Comprimido que se coloca bajo la lengua',1),
('Polvo para reconstituir','Polvo que se mezcla con líquido antes de administración',1),
('Jarabe','Solución líquida dulce para administración oral',1),
('Suspensión oral','Líquido con partículas sólidas dispersas para administración oral',1),
('Solución oral','Líquido completamente disuelto para administración oral',1),
('Gotas oftálmicas','Solución para administración en ojos',1),
('Gotas óticas','Solución para administración en oídos',1),
('Gotas nasales','Solución para administración en la nariz',1),
('Spray nasal','Solución o suspensión administrada por vía nasal',1),
('Inhalador','Aerosol para administración respiratoria',1),
('Nebulizador','Líquido para ser vaporizado y administrado por inhalación',1),
('Crema','Preparación semisólida para aplicar sobre la piel',1),
('Pomada','Preparación semisólida con base grasa para la piel',1),
('Ungüento','Preparación semisólida con efecto terapéutico sobre la piel',1),
('Gel','Preparación semisólida acuosa o hidroalcohólica para aplicación tópica',1),
('Parche transdérmico','Sistema adhesivo que libera fármaco a través de la piel',1),
('Suppositorio','Forma sólida para administración rectal o vaginal',1),
('Óvulo vaginal','Forma sólida para administración vaginal',1),
('Solución inyectable','Solución estéril para vía parenteral',1),
('Concentrado inyectable','Solución concentrada que se diluye antes de administrar',1),
('Polvo inyectable','Polvo estéril que se reconstituye antes de usar',1),
('Ampolla','Envase estéril para administración parenteral',1),
('Frasco vial','Envase para múltiples dosis inyectables',1),
('Implante subcutáneo','Dispositivo que libera fármaco lentamente bajo la piel',1),
('Pasta oral','Preparación semisólida para administración bucal',1),
('Colirio','Preparación líquida para el ojo',1),
('Spray bucal','Solución pulverizable para la cavidad oral',1),
('Enema','Solución líquida para administración rectal',1),
('Microtableta','Pequeña tableta para administración oral',1),
('Pellets','Pequeñas partículas esféricas que contienen fármaco',1),
('Granulado','Pequeñas partículas sólidas para disolver o ingerir',1),
('Polvo oral','Polvo que se mezcla con líquidos antes de administrar',1),
('Jarabe pediátrico','Jarabe formulado para niños',1),
('Suspensión pediátrica','Suspensión líquida para administración a niños',1),
('Capsula gelatinosa','Cápsula hecha de gelatina para administración oral',1),
('Pastilla','Comprimido sólido para administración oral',1),
('Solución tópica','Líquido aplicado sobre la piel',1),
('Crema tópica','Preparación semisólida para uso cutáneo',1),
('Ungüento oftálmico','Preparación semisólida para el ojo',1),
('Gotas óticas','Preparación líquida para oído',1),
('Spray oftálmico','Solución pulverizable para el ojo',1),
('Loción','Preparación líquida para aplicación cutánea',1),
('Aceite medicinal','Preparación líquida grasa para aplicación tópica o oral',1),
('Champú medicado','Líquido con agentes terapéuticos para el cabello y cuero cabelludo',1),
('Solución antiséptica','Líquido para desinfección de la piel',1),
('Gel anestésico','Preparación semisólida para anestesia tópica',1),
('Tiras reactivas','Tiras que detectan sustancias específicas',1),
('Parche bucal','Parche que libera fármaco en la cavidad oral',1),
('Tableta subcutánea','Tableta diseñada para absorción subcutánea',1),
('Spray vaginal','Solución administrada por vía vaginal',1),
('Gel vaginal','Preparación semisólida para administración vaginal',1),
('Crema vaginal','Preparación semisólida para uso vaginal',1),
('Tableta disoluble','Comprimido que se disuelve rápidamente en la boca',1),
('Polvo efervescente','Polvo que genera efervescencia al disolverse',1),
('Gragea','Comprimido recubierto para deglución fácil',1),
('Tableta recubierta','Comprimido con capa protectora o sabor',1),
('Tableta recubierta de azúcar','Comprimido recubierto con azúcar para saborizar',1),
('Tableta recubierta de película','Comprimido recubierto con película protectora',1),
('Tableta liberación prolongada','Comprimido que libera fármaco lentamente',1),
('Tableta de liberación controlada','Comprimido con liberación controlada del fármaco',1),
('Tableta de liberación inmediata','Comprimido que libera rápidamente el fármaco',1),
('Cápsula de liberación prolongada','Cápsula que libera fármaco lentamente',1),
('Cápsula de liberación controlada','Cápsula con liberación controlada del fármaco',1),
('Cápsula de liberación inmediata','Cápsula que libera rápidamente el fármaco',1),
('Granulado para suspensión','Granulado para preparar suspensión líquida',1),
('Microgranulado','Pequeño gránulo para administración oral o reconstitución',1),
('Suspensión oftálmica','Líquido con partículas para uso ocular',1),
('Solución oftálmica','Líquido completamente disuelto para el ojo',1),
('Pomada oftálmica','Preparación semisólida para el ojo',1),
('Gota oral','Preparación líquida administrada por vía oral',1),
('Tableta masticable pediátrica','Tableta diseñada para niños',1),
('Cápsula pediátrica','Cápsula diseñada para administración infantil',1),
('Suplemente alimenticio sólido','Preparación sólida para aporte nutricional',1),
('Suplemente alimenticio líquido','Preparación líquida para aporte nutricional',1),
('Goma masticable','Forma sólida masticable para administración oral',1),
('Pastilla efervescente','Pastilla que genera efervescencia al disolverse',1),
('Gotas sublinguales','Gotas administradas debajo de la lengua',1),
('Tableta sublingual pediátrica','Comprimido sublingual para niños',1),
('Solución oral pediátrica','Líquido administrado oralmente a niños',1),
('Gel oral','Preparación semisólida administrada por vía oral',1),
('Spray oral pediátrico','Spray para administración oral a niños',1),
('Tableta dispersable','Comprimido que se dispersa en agua',1),
('Cápsula dispersable','Cápsula que se dispersa en líquido antes de ingerir',1),
('Spray dérmico','Spray para aplicación sobre piel',1),
('Solución dérmica','Solución líquida aplicada sobre piel',1),
('Pomada dérmica','Preparación semisólida para piel',1),
('Crema dérmica','Preparación semisólida para piel',1),
('Loción dérmica','Preparación líquida para piel',1),
('Gel dérmico','Preparación semisólida acuosa para piel',1),
('Tableta oral soluble','Comprimido que se disuelve rápidamente en la boca',1),
('Tableta oral dispersable','Comprimido que se dispersa en líquido antes de ingerir',1),
('Cápsula oral dispersable','Cápsula que se dispersa en líquido antes de ingerir',1),
('Inhalador pediátrico','Aerosol para administración respiratoria en niños',1),
('Nebulizador pediátrico','Líquido para nebulización en niños',1),
('Spray nasal pediátrico','Spray para vía nasal en niños',1),
('Parche transdérmico pediátrico','Parche que libera fármaco en piel de niños',1),
('Tableta para disolver bajo lengua','Comprimido sublingual de disolución rápida',1),
('Tableta masticable de liberación prolongada','Tableta que se mastica y libera fármaco lentamente',1),
('Cápsula de liberación sostenida','Cápsula que mantiene liberación constante',1),
('Cápsula gelatinosa de liberación prolongada','Cápsula de gelatina que libera lentamente',1),
('Tableta de liberación retardada','Tableta que retarda liberación de fármaco',1),
('Granulado efervescente','Gránulo que genera efervescencia al disolverse',1),
('Polvo efervescente para bebida','Polvo que se disuelve y efervescente en líquido',1),
('Spray oral de sabor','Spray líquido para administración oral con sabor',1),
('Tableta masticable de vitamina','Comprimido masticable para aporte vitamínico',1),
('Cápsula blanda de aceite','Cápsula blanda que contiene aceite medicinal',1),
('Gel lubricante medicado','Gel para aplicación terapéutica y lubricación',1),
('Crema antimicótica','Preparación semisólida para hongos en piel',1),
('Pomada antibacteriana','Preparación semisólida con antibiótico tópico',1),
('Ungüento cicatrizante','Preparación tópica que favorece cicatrización',1),
('Solución antiséptica dérmica','Líquido para desinfección cutánea',1),
('Loción capilar medicada','Líquido para tratamiento terapéutico del cuero cabelludo',1),
('Champú anticaspa','Preparación líquida para control de caspa',1),
('Gel analgésico','Preparación semisólida para alivio del dolor',1),
('Gel antiinflamatorio','Preparación tópica con efecto antiinflamatorio',1),
('Spray antiinflamatorio','Spray para aplicación tópica con efecto antiinflamatorio',1),
('Parche analgésico','Parche que libera analgésico a través de la piel',1),
('Parche antiprurítico','Parche que alivia picazón y libera fármaco',1),
('Tableta sublingual rápida','Comprimido que se disuelve rápidamente bajo la lengua',1),
('Tableta bucal de acción rápida','Comprimido que se disuelve en la boca',1),
('Spray bucal anestésico','Spray para anestesia local en boca',1),
('Enjuague bucal medicado','Líquido para enjuague con efecto terapéutico',1),
('Goma de mascar medicinal','Goma masticable con principios activos',1),
('Cápsula inhalable','Cápsula con polvo para inhalación',1),
('Polvo inhalable','Polvo seco para administración respiratoria',1),
('Aerosol nasal','Preparación líquida pulverizada en nariz',1),
('Nebulizador para adultos','Líquido para vaporización respiratoria',1),
('Nebulizador para pediatría','Líquido para inhalación en niños',1),
('Cápsula de vitamina','Cápsula sólida con vitaminas',1),
('Tableta de suplemento mineral','Comprimido con minerales esenciales',1),
('Polvo nutritivo','Preparación en polvo para nutrición oral',1),
('Granulado vitaminado','Gránulo con vitaminas para diluir o tomar',1),
('Tableta de desintegración rápida','Comprimido que se desintegra rápido en boca',1),
('Cápsula de liberación inmediata','Cápsula que libera el fármaco rápidamente',1),
('Tableta de acción prolongada','Tableta que libera fármaco lentamente',1),
('Cápsula masticable','Cápsula que se mastica antes de tragar',1),
('Tableta de succión bucal','Tableta que se disuelve lentamente en la boca',1),
('Tableta bucodispersable','Comprimido que se dispersa en la boca',1),
('Tableta efervescente pediátrica','Comprimido efervescente para niños',1),
('Suspensión líquida pediátrica','Líquido con partículas para administración infantil',1),
('Solución oral pediátrica','Líquido completamente disuelto para niños',1),
('Gotas oftálmicas pediátricas','Solución para ojos de niños',1),
('Colirio pediátrico','Preparación líquida para administración ocular infantil',1),
('Spray nasal pediátrico','Solución pulverizable para niños en nariz',1),
('Crema pediátrica','Preparación semisólida para uso infantil',1),
('Pomada pediátrica','Preparación semisólida con base grasa para niños',1),
('Ungüento pediátrico','Preparación tópica para niños',1),
('Gel pediátrico','Preparación semisólida acuosa para niños',1),
('Parche transdérmico pediátrico','Parche que libera fármaco en niños',1),
('Tableta de vitamina masticable','Comprimido de vitaminas para masticar',1),
('Cápsula de aceite de pescado','Cápsula blanda con omega-3',1),
('Tableta de hierro','Comprimido con suplemento de hierro',1),
('Tableta de calcio','Comprimido con suplemento de calcio',1),
('Tableta de vitamina C','Comprimido con vitamina C',1),
('Tableta de vitamina D','Comprimido con vitamina D',1),
('Cápsula multivitamínica','Cápsula con varias vitaminas',1),
('Tableta de magnesio','Comprimido con suplemento de magnesio',1),
('Cápsula de zinc','Cápsula con suplemento de zinc',1),
('Polvo para bebida energética','Polvo para preparar bebida con vitaminas y minerales',1),
('Granulado para bebida con vitaminas','Granulado para preparar bebida enriquecida',1),
('Jarabe vitamínico','Líquido con vitaminas para administración oral',1),
('Gotas vitamínicas','Líquido con vitaminas para administración oral',1),
('Solución vitamínica oral','Líquido completamente disuelto con vitaminas',1),
('Tableta de desintoxicación','Comprimido para apoyo de desintoxicación',1),
('Cápsula de desintoxicación','Cápsula con principios activos de desintoxicación',1),
('Tableta energizante','Comprimido con efecto estimulante',1),
('Cápsula energizante','Cápsula con efecto estimulante',1),
('Goma energizante','Goma masticable con efecto estimulante',1),
('Polvo energizante','Polvo con efecto estimulante para bebida',1),
('Tableta de relajación','Comprimido con efecto calmante',1),
('Cápsula de relajación','Cápsula con efecto calmante',1),
('Gotas relajantes','Solución líquida con efecto calmante',1),
('Spray relajante','Preparación pulverizable con efecto calmante',1),
('Parche calmante','Parche transdérmico con efecto sedante',1),
('Tableta digestiva','Comprimido para mejorar digestión',1),
('Cápsula digestiva','Cápsula para mejorar digestión',1),
('Gotas digestivas','Preparación líquida para digestión',1),
('Tableta para el sueño','Comprimido con efecto hipnótico',1),
('Cápsula para dormir','Cápsula con efecto sedante',1),
('Spray oral para dormir','Preparación pulverizable con efecto sedante',1),
('Parche para dormir','Parche transdérmico con efecto calmante',1),
('Gel bucal','Preparación semisólida para boca',1),
('Crema bucal','Preparación semisólida para cavidad oral',1),
('Pomada bucal','Preparación semisólida para encías y boca',1),
('Tableta antigripal','Comprimido para aliviar síntomas de gripe',1),
('Jarabe antigripal','Líquido para aliviar síntomas gripales',1),
('Gotas antigripales','Preparación líquida para síntomas gripales',1),
('Spray nasal antigripal','Spray para aliviar congestión nasal',1),
('Tableta analgésica','Comprimido para aliviar dolor',1),
('Cápsula analgésica','Cápsula para alivio del dolor',1),
('Gotas analgésicas','Solución líquida para dolor',1),
('Spray analgésico','Preparación pulverizable para dolor',1),
('Parche analgésico tópico','Parche para alivio del dolor localizado',1),
('Gel analgésico tópico','Gel para alivio del dolor localizado',1),
('Crema analgésica','Preparación semisólida para dolor',1),
('Pomada analgésica','Preparación semisólida para alivio del dolor',1),
('Tableta antiinflamatoria','Comprimido con efecto antiinflamatorio',1),
('Cápsula antiinflamatoria','Cápsula con efecto antiinflamatorio',1),
('Gotas antiinflamatorias','Preparación líquida antiinflamatoria',1),
('Spray antiinflamatorio','Spray con efecto antiinflamatorio',1),
('Parche antiinflamatorio','Parche con efecto antiinflamatorio',1),
('Gel antiacné','Preparación semisólida para tratamiento del acné',1),
('Crema antiacné','Preparación semisólida tópica para acné',1),
('Loción antiacné','Líquido terapéutico para tratamiento del acné',1),
('Espuma limpiadora facial','Preparación espumosa para limpieza facial',1),
('Jabón medicado','Jabón con principios activos terapéuticos',1),
('Toallitas faciales medicadas','Toallitas impregnadas con principios activos',1),
('Solución desinfectante','Líquido para desinfección de heridas',1),
('Gel antibacteriano','Gel para limpieza y desinfección de manos',1),
('Spray antibacteriano','Spray para limpieza de manos y superficies',1),
('Crema cicatrizante','Preparación semisólida que favorece cicatrización',1),
('Pomada cicatrizante','Preparación semisólida con efecto cicatrizante',1),
('Ungüento cicatrizante','Ungüento terapéutico para heridas',1),
('Spray cicatrizante','Preparación pulverizable para heridas',1),
('Parche cicatrizante','Parche transdérmico que favorece cicatrización',1),
('Tableta para alergias','Comprimido para aliviar síntomas de alergia',1),
('Cápsula para alergias','Cápsula con principio activo antihistamínico',1),
('Gotas para alergias','Preparación líquida antihistamínica',1),
('Spray nasal para alergias','Spray nasal antihistamínico',1),
('Crema antihistamínica','Preparación tópica para aliviar picazón',1),
('Gel antihistamínico','Preparación semisólida para alivio de picazón',1),
('Tableta vitamínica masticable','Comprimido vitamínico para masticar',1),
('Tableta vitamínica efervescente','Comprimido efervescente con vitaminas',1),
('Tableta vitamínica dispersable','Comprimido que se dispersa en líquido con vitaminas',1),
('Cápsula vitamínica','Cápsula sólida con vitaminas',1),
('Gotas vitamínicas pediátricas','Preparación líquida de vitaminas para niños',1),
('Jarabe vitamínico pediátrico','Líquido con vitaminas para niños',1),
('Spray vitamínico','Spray oral con vitaminas',1),
('Goma de vitaminas','Goma masticable con vitaminas',1),
('Tableta mineral','Comprimido con minerales esenciales',1),
('Cápsula mineral','Cápsula con minerales',1),
('Polvo mineral para bebida','Polvo para preparar bebida con minerales',1),
('Granulado mineral','Gránulo para preparación de bebida con minerales',1),
('Tableta energizante pediátrica','Comprimido para aportar energía a niños',1),
('Goma energizante pediátrica','Goma masticable con efecto estimulante para niños',1),
('Polvo energizante pediátrico','Polvo para bebida energética infantil',1),
('Spray energético','Spray oral con efecto estimulante',1),
('Cápsula energética','Cápsula con efecto estimulante',1),
('Tableta digestiva pediátrica','Comprimido para mejorar digestión infantil',1),
('Cápsula digestiva pediátrica','Cápsula con efecto digestivo para niños',1),
('Gotas digestivas pediátricas','Preparación líquida para digestión en niños',1),
('Tableta para el sueño pediátrica','Comprimido sedante para niños',1),
('Cápsula para dormir pediátrica','Cápsula sedante para niños',1),
('Spray para dormir pediátrico','Spray oral con efecto sedante para niños',1),
('Parche para dormir pediátrico','Parche transdérmico sedante para niños',1),
('Gel bucal pediátrico','Preparación semisólida para cavidad oral infantil',1),
('Crema bucal pediátrica','Preparación semisólida para encías de niños',1),
('Pomada bucal pediátrica','Preparación semisólida para boca infantil',1),
('Tableta antigripal pediátrica','Comprimido para síntomas gripales en niños',1),
('Jarabe antigripal pediátrico','Líquido para aliviar síntomas de gripe infantil',1),
('Gotas antigripales pediátricas','Preparación líquida para gripe infantil',1),
('Spray nasal antigripal pediátrico','Spray para congestión nasal infantil',1),
('Tableta analgésica pediátrica','Comprimido para aliviar dolor en niños',1),
('Cápsula analgésica pediátrica','Cápsula para alivio de dolor infantil',1),
('Gotas analgésicas pediátricas','Preparación líquida para dolor infantil',1),
('Spray analgésico pediátrico','Spray pulverizable para dolor en niños',1),
('Parche analgésico pediátrico','Parche para alivio localizado en niños',1),
('Gel analgésico pediátrico','Gel para alivio del dolor en niños',1),
('Crema analgésica pediátrica','Preparación tópica para dolor infantil',1),
('Pomada analgésica pediátrica','Preparación tópica semisólida para dolor infantil',1),
('Tableta antiinflamatoria pediátrica','Comprimido con efecto antiinflamatorio en niños',1),
('Cápsula antiinflamatoria pediátrica','Cápsula con efecto antiinflamatorio infantil',1),
('Gotas antiinflamatorias pediátricas','Preparación líquida antiinflamatoria para niños',1),
('Spray antiinflamatorio pediátrico','Spray pulverizable antiinflamatorio para niños',1),
('Parche antiinflamatorio pediátrico','Parche transdérmico con efecto antiinflamatorio infantil',1),
('Gel antiacné pediátrico','Preparación semisólida para acné infantil',1),
('Crema antiacné pediátrica','Preparación tópica para acné en niños',1),
('Loción antiacné pediátrica','Líquido terapéutico para acné infantil',1),
('Espuma limpiadora facial pediátrica','Preparación espumosa para limpieza facial infantil',1),
('Jabón medicado pediátrico','Jabón terapéutico para niños',1),
('Toallitas faciales medicadas pediátricas','Toallitas con principios activos para niños',1),
('Solución desinfectante pediátrica','Líquido para desinfección de piel infantil',1),
('Gel antibacteriano pediátrico','Gel para limpieza y desinfección infantil',1),
('Spray antibacteriano pediátrico','Spray para limpieza infantil',1),
('Crema cicatrizante pediátrica','Preparación semisólida que favorece cicatrización infantil',1),
('Pomada cicatrizante pediátrica','Preparación semisólida para cicatrización infantil',1),
('Ungüento cicatrizante pediátrico','Ungüento para cicatrización en niños',1),
('Spray cicatrizante pediátrico','Preparación pulverizable para cicatrización infantil',1),
('Parche cicatrizante pediátrico','Parche transdérmico cicatrizante para niños',1),
('Tableta para alergias pediátrica','Comprimido para síntomas de alergia en niños',1),
('Cápsula para alergias pediátrica','Cápsula antihistamínica para niños',1),
('Gotas para alergias pediátricas','Preparación líquida antihistamínica infantil',1),
('Spray nasal para alergias pediátrico','Spray antihistamínico para niños',1),
('Crema antihistamínica pediátrica','Preparación tópica para picazón infantil',1),
('Gel antihistamínico pediátrico','Preparación semisólida para alivio de picazón en niños',1);
